version: "3.7"

x-common-variables: &common-variables
  POSTGRES_DB: stori_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_db_stori
    ports:
      - "54320:5432"
    environment: *common-variables
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stori_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  stori:
    
volumes:
  pg_data:
