version: "3.8"

x-common-variables: &common-variables
  POSTGRES_DB: stori_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432

x-dsn-variables: &dsn-variables
  DSN_DB: postgres://postgres:postgres@postgres_db_stori:5432/stori_db?sslmode=disable
  SG_KEY: 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

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_db_stori
    ports:
      - "54320:5432"
    expose:
      - "54320"
    environment: *common-variables
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stori_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/

  api:
    image: stori:latest
    container_name: service_stori
    restart: on-failure
    ports:
      - "8080:8080"
    environment: *dsn-variables
    depends_on:
      - postgres

networks:
  default:
    name: "stori.dev"

volumes:
  pg_data:
