version: "3.8"

x-common-variables: &common-variables
  POSTGRES_DB: stori
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: db.stori.dev
    ports:
      - "54320:5432"
    expose:
      - "54320"
    environment: *common-variables
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stori" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_stori_data:/var/lib/postgresql/data/

  api:
    image: stori:latest
    container_name: app.stori.dev
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  default:
    name: "stori.dev"

volumes:
  pg_stori_data:
